version: "3.9"

services:
  omoponfhir:
    image: elizabethshivers/omoponfhir
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://omop54:5432/omop54
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - SERVERBASE_URL=http://localhost:8080/omoponfhir/fhir
      - SMART_INTROSPECTURL=http://localhost:8080/smart/introspect
      - SMART_AUTHSERVERURL=http://localhost:8080/smart/authorize
      - SMART_TOKENSERVERURL=http://localhost:8080/smart/token
      - AUTH_BEARER=12345
      - AUTH_BASIC=client:secret
      - FHIR_READONLY=False
      - MEDICATION_TYPE=code
    depends_on:
      - omop54

  omop54:
    image: elizabethshivers/omopcdm54postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - CONSTRAINTS=false
    volumes:
      - ./vocab:/VOCAB
